runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app --timeout 240

runtime_config:
  python_version: 3

#[START env]
env_variables:
    # Replace user, password, database, and instance connection name with the values obtained
    # when configuring your Cloud SQL instance.
    SQLALCHEMY_DATABASE_URI: >-
      postgresql+psycopg2://proxy_test:ThisTookTooLong@/WeatherTables?host=/cloudsql/teamthundersnow-198022:us-central1:dcweather
 
#liveness_check:
#    check_interval_sec: 300
#[END env]

#[START cloudsql_settings]
# Replace project and instance with the values obtained  when configuring your
# Cloud SQL instance.
beta_settings:
    cloud_sql_instances: teamthundersnow-198022:us-central1:dcweather
#[END cloudsql_settings]